# Generated by Django 5.0.6 on 2024-05-08 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('dia_publicacion', models.DateField()),
                ('cantidad_videos', models.IntegerField()),
                ('imagen', models.ImageField(blank=True, null=True, upload_to='cursos_imagenes/')),
            ],
        ),
    ]
